### ISSUE TITLE
Cannot re-create environment that worked previously. "warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY"

### ISSUE THREAD

**Issue by peterroelants** [conda/conda-libmamba-solver#206] opened 2023-05-15 15:13 UTC
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I cannot rebuild an environment that I had working previously (same machine, same .yml). Particularly I'm getting this warning I haven't seen before: `warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY`

```
❯ mamba env create --file ./env/base_conda_env.yml --name jax_cuda
conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
nvidia/linux-64                                             Using cache
nvidia/noarch                                               Using cache


Looking for: ["pip[version='>=23']", "python[version='>=3.10,<3.12']", "cuda-nvcc[version='>=11,<13']", 'cudnn', "jax[version='>=0.4.3,<1']", "jaxlib[version='>=0.4.3,<1']", "jaxtyping[version='>=0.2.11,<1']", "joblib[version='>=1.2.0,<2']", "pandas[version='>=1.5.3,<2']", "numpy[version='>=1.23,<2']", "scipy[version='>=1.10,<2']", "xarray[version='>=2023.2,<2024']", "numba[version='>=0.51,<1']"]


warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
└─ cuda-nvcc >=11,<13  is installable with the potential options
   ├─ cuda-nvcc 12.0.76 would require
   │  └─ cuda-version >=12.0,<12.1.0a0 , which requires
   │     └─ __cuda >=12 , which can be installed;
   └─ cuda-nvcc [11.3.58|11.4.100|...|12.1.66] conflicts with any installable versions previously reported.
```

With `./env/base_conda_env.yml`:
```yaml
channels:
  - conda-forge
  - nvidia
dependencies:
  # Python interpreter and Pip
  - pip>=23
  - python>=3.10,<3.12
  # CUDA (Uncomment this if installing for CPU!)
  - cuda-nvcc>=11,<13
  - cudnn
  # JAX
  - jax>=0.4.3,<1
  - jaxlib>=0.4.3,<1
  - jaxtyping>=0.2.11,<1
  # Packages
  - joblib>=1.2.0,<2
  - pandas>=1.5.3,<2
  - numpy>=1.23,<2
  - scipy>=1.10,<2
  - xarray>=2023.2,<2024
  - numba>=0.51,<1
  - pip:
      - molmass>=2022.12,<2024
      - simple-pytree>=0.2.0,<1
```

### Conda Info

```shell
❯ conda info

     active environment : None
            shell level : 0
       user config file : /home/peter/.condarc
 populated config files : /home/peter/mambaforge/.condarc
                          /home/peter/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.6=0
                          __glibc=2.31=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /home/peter/mambaforge  (writable)
      conda av data dir : /home/peter/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/peter/mambaforge/pkgs
                          /home/peter/.conda/pkgs
       envs directories : /home/peter/mambaforge/envs
                          /home/peter/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.6 Linux/5.14.0-1059-oem ubuntu/20.04.6 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
❯ conda config --show-sources
==> /home/peter/mambaforge/.condarc <==
channels:
  - conda-forge

==> /home/peter/.condarc <==
auto_activate_base: False
channel_priority: strict
```

### Conda list

```shell
❯ conda list --show-channel-urls
# packages in environment at /home/peter/mambaforge:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     23.3.1          py310hff52083_0    conda-forge
conda-package-handling    1.8.1           py310h5764c6d_1    conda-forge
cryptography              38.0.4          py310h600f1e7_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libarchive                3.6.2                h3d51595_0    conda-forge
libcurl                   7.88.1               hdc1c0ab_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.1.0              h8d9b700_16    conda-forge
libgomp                   12.1.0              h8d9b700_16    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmamba                  1.4.2                hcea66bb_0    conda-forge
libmambapy                1.4.2           py310h1428755_0    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.23               h3eb15da_0    conda-forge
libsqlite                 3.39.2               h753d276_1    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.10.3               hfdac1af_6    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.4.2           py310h51d5547_0    conda-forge
ncurses                   6.3                  h27087fc_1    conda-forge
openssl                   3.1.0                hd590300_3    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py310h5764c6d_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py310hff52083_5    conda-forge
python                    3.10.6          ha86cf86_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21         py310h1fa729e_3    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
ruamel_yaml               0.15.80         py310h5764c6d_1007    conda-forge
setuptools                65.2.0          py310hff52083_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_1    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

### Additional Context

Previously I have been able to create this environment without any issues with CUDA working.

**Comment by jaimergp** [comment] 2023-05-15 15:52
Hi @peterroelants, the warning might be expected because we enabled `libmamba`'s new feature for conflict explanation; I don't think that's the cause here.

I am more inclined to think this could be a change in the `nvidia` channel, strict priority, and the fact that conda-forge is slowly adding `cuda-*` packages. Can you reproduce this problem with any other solver? e.g. conda classic, `mamba`, or `micromamba`?

**Comment by jaimergp** [comment] 2023-05-15 16:13
I can reproduce with strict priority, but it does solve with flexible.

```
$ CONDA_CHANNEL_PRIORITY=flexible mamba env create --file ./env/base_conda_env.yml --name jax_cuda
```

You could try updating your GPU drivers. Your reported `__cuda=11.6` might not be enough. You can test the solver behavior with:

```
$ CONDA_OVERRIDE_CUDA=12 mamba ...
```

**Comment by peterroelants** [comment] 2023-05-15 17:12
> I can reproduce with `mamba` and strict priority, but it does solve with flexible.

Thanks, `CONDA_CHANNEL_PRIORITY=flexible` does seem to solve the issue.

**Comment by peterroelants** [comment] 2023-05-15 17:14
> Btw, I had assumed you were using `conda-libmamba-solver` but I think you are using plain `mamba`. Is that correct? Maybe you need to report it in `mamba-org/mamba`.

I'm sorry, I wasn't aware there was a difference. Would it be good practices to still report this to `mamba-org/mamba`?

Now I'm curious, what is the main difference between `mamba` and `conda-libmamba-solver`. And is one recommended above the other?

**Comment by jaimergp** [comment] 2023-05-17 09:10
The mamba project is maintained but a different team and organization, so I'd say they would appreciate the report so they can fix this or give you more specific information.

`conda-libmamba-solver` integrates the `libmamba` library in `conda`; `mamba` is aiming to become a full C++ rewrite of `conda`. There's an emphasis on backwards compatibility with `conda` classic (the former solver) in this project, while the `mamba` one doesn't need to worry about that. That might involve behavioural differences in more complicated solves (more constrained), but it should be essentially the same for new envs / simpler solves.

In your issue, I can actually solve your problematic env with both `conda-libmamba-solver` and `micromamba`, so the issue is on the `mamba` side. I am going to close this one but please consider getting in touch with `mamba-org/mamba` to see if there's something they need to fix!

**Closed by jaimergp** 2023-05-17 09:10 UTC
Labels: type::support
